changes to allow yaml to be parsed

diff --git a/template/.github/workflows/e2e-html-reporting.yaml b/template/.github/workflows/e2e-html-reporting.yaml
--- a/template/.github/workflows/e2e-html-reporting.yaml
+++ b/template/.github/workflows/e2e-html-reporting.yaml
@@ -33,11 +33,11 @@ jobs:
       checks: write
       packages: write
 
-    steps:
-      - name: E2E SIT Test Report
-        if: "${{ success() || failure() }}" # run this step even if previous step failed
-        continue-on-error: true
-        run: |
-          OWNER_REPO_NAME=${{ github.repository }}
-          REPO_NAME=$(echo "$OWNER_REPO_NAME" | cut -d'/' -f2)
-          echo "End-2-End SIT NScenario Test Report : https://${{ github.repository_owner }}.github.io/$REPO_NAME/htmlReports/${{ github.ref_name }}/index.html"
+#    steps:
+#      - name: E2E SIT Test Report
+#        if: "${{ success() || failure() }}" # run this step even if previous step failed
+#        continue-on-error: true
+#        run: |
+#          OWNER_REPO_NAME=${{ github.repository }}
+#          REPO_NAME=$(echo "$OWNER_REPO_NAME" | cut -d'/' -f2)
+#          echo "End-2-End SIT NScenario Test Report : https://${{ github.repository_owner }}.github.io/$REPO_NAME/htmlReports/${{ github.ref_name }}/index.html"
